SELECT GETDATE()

SELECT DATEADD(DAY, 1, '30-05-2026')

SELECT DATEDIFF(YEAR, '31-05-1985', GETDATE())

SELECT DAY('17-07-2010') AS tempo_de_casa

SELECT MONTH('17-07-2010') AS tempo_de_casa

SELECT YEAR('17-07-2010') AS tempo_de_casa


SELECT nome, DATEDIFF(YEAR, DATA_ADMISSAO, GETDATE()) AS tempo_de_casa
FROM funcionario
ORDER BY tempo_de_casa DESC

SELECT nome, MONTH(DATA_ADMISSAO)
FROM funcionario
WHERE MONTH(DATA_ADMISSAO) = MONTH(GETDATE())

SELECT nome, DATA_ADMISSAO
FROM funcionario
WHERE DATEDIFF(YEAR, DATA_ADMISSAO, GETDATE()) >=10

SELECT nome,CONVERT(VARCHAR, GETDATE(),108)

SELECT nome,CONVERT(VARCHAR, GETDATE(),111)

SELECT nome,CONVERT(VARCHAR, GETDATE(),112)

SELECT nome,CONVERT(VARCHAR, GETDATE(),113)

SELECT EOMONTH(GETDATE())

SELECT FORMAT(GETDATE(),'d', 'PT-BR')
